---
- name: Install Tomcat and PetClinic
  hosts: all
  become: true

  tasks:

   - name: Update Distribution
     apt:
       upgrade: dist
       update_cache: yes

   - name: Installs JRE
     apt:
       name: default-jre
       state: latest
       install_recommends: no

   - name: Installs Tomcat8 web server
     apt: pkg=tomcat8 state=present update_cache=true
     notify:
       - start Tomcat

   - name: Copy spring-petclinic webapp to /var/lib/tomcat8/webapps
     copy:
       src:  ~/spring-framework-petclinic/target/petclinic.war
       dest: /var/lib/tomcat8/webapps/petclinic.war
       owner: ubuntu
       group: ubuntu
     notify:
       - restart Tomcat

 handlers:
 
   - name: start Tomcat
     service: name=tomcat8 state=started

   - name: restart Tomcat
     service: name=tomcat8 state=restarted
